import ProfileUpdate from "@/components/auth/ProfileUpdate";

export const metadata = {
  title: "User Profile",
  description: "Generated by kamal create next app",
};

const ProfilePage = () => {
  return (
    <div>
      <ProfileUpdate />
    </div>
  );
};

export default ProfilePage;
