import { Poppins, Urbanist, Hind_Siliguri, } from "next/font/google";
import "./globals.css";

const urban = Urbanist({
  variable: "--font-urban",
  subsets: ["latin"]

})
const siliguri = Hind_Siliguri({
  variable: "--font-siliguri",
  subsets: ["latin"]
})


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
});


export const metadata = {
  title: "Royal Tiles",
  description: "Generated by kamal create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${urban.variable}  ${poppins.variable} ${siliguri.variable} h-screen antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <main className="min-h-screen">{children}</main>
      </body>
    </html>
  );
}
