import Banner from "@/components/home/Banner";
import FeatureTiles from "@/components/home/FeatureTiles";
import TopMarquee from "@/components/home/Marquee";
import CollectionTiles from "@/components/home/CollectionTiles";
import WhyChoose from "@/components/home/WhyChoose";
import TileShowroom from "@/components/home/TileShowroom";
import Brands from "@/components/home/Brands";

export const metadata = {
  title: "Royal Tiles",
  description: "Generated by kamal create next app",
};

export default function Home() {
  return (
    <>
      <Banner />
      <TopMarquee />
      <FeatureTiles />
      <CollectionTiles />
      <Brands />
      <WhyChoose />
      <TileShowroom />
    </>
  )
}
