import TilesAll from "@/components/totalTiles/TilesAll";

export const metadata = {
  title: "Premium all tiles",
  description: "Generated by kamal create next app",
};

const AllTilesPage = () => {
  return (
    <>
      <TilesAll />
    </>
  );
};

export default AllTilesPage;
