import RegisterForm from "@/components/auth/RegisterForm";

export const metadata = {
  title: "SignUp Page",
  description: "Generated by kamal create next app",
};

const RegisterPage = () => {
  return (
    <div className="min-h-screen flex items-center justify-center ">
      <RegisterForm />
    </div>
  );
};

export default RegisterPage;
