import { Poppins, Urbanist, Hind_Siliguri, } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import PageTransition from "@/components/shared/PageTransition";

const urban = Urbanist({
  variable: "--font-urban",
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],

})
const siliguri = Hind_Siliguri({
  variable: "--font-siliguri",
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
})


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
});


export const metadata = {
  title: "Royal Tiles",
  description: "Generated by kamal create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      suppressHydrationWarning
      className={`${urban.variable}  ${poppins.variable} ${siliguri.variable} h-screen antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <main className="min-h-screen">
          <PageTransition>
            {children}
          </PageTransition>
          <ToastContainer />
        </main>
      </body>
    </html>
  );
}
