import LoginForm from "@/components/auth/LoginForm";

export const metadata = {
  title: "Login Page",
  description: "Generated by kamal create next app",
};

const LoginPage = () => {
  return (
    <div className="min-h-screen flex items-center justify-center bg-background  px-4 transition-colors">
      <LoginForm />
    </div>
  );
};

export default LoginPage;
